export const TILE_SIZE = 128;

export const PLAYER_RENDER_SIZE = TILE_SIZE;
export const SMALL_PLAYER_RENDER_SIZE = PLAYER_RENDER_SIZE * 0.8;

export const DOOR_TOP_OFFSET = TILE_SIZE;

export const COIN_POP_SIZE = TILE_SIZE * 0.6;
export const COIN_POP_HEIGHT = TILE_SIZE * 1.5;
export const COIN_POP_DURATION = 500;

export const DAMAGE_SHAKE_DURATION = 200;
export const DAMAGE_SHAKE_INTENSITY = 0.007;

export const DEATH_SHAKE_DURATION = 150;
export const DEATH_SHAKE_INTENSITY = 0.012;
export const FALL_RESTART_DELAY = 300;
export const DEATH_RESTART_DELAY = 1500;

export const LEVEL_COMPLETE_SLIDE_DURATION = 400;
export const  LEVEL_COMPLETE_FADE_DURATION = 300;
export const LEVEL_COMPLETE_FLASH_DURATION = 500;
export const LEVEL_COMPLETE_CALLBACK_DELAY = 400;
